plugins/auth/fps_auth/config.py
plugins/auth/fps_auth/routes.py
plugins/auth/setup.py

Description
---
Use `fps` configuration to store auth static secrets/config
Add the corresponding `entry_point`
This allows you to configure the plugin:
- from a config file (`fps.toml`, `authenticator.toml` or any other file passed as a CLI argument using `--config=<file>.toml`)
```
[authenticator]
client_id = "foo"
```
- from the CLI by passing one of the following extra args
- `--authenticator.client_id=foo`
- `--authenticator.client_id="foo"`
-  `--authenticator.client_id foo`
-  `--authenticator.client_id "foo"`
Note: 
- the `authenticator` name comes from the additional `n = register_plugin_name("authenticator")`
- if you decide to change it, it will be automatically reflected in 
- the config filenames `<plugin-name>.toml`
- the section name `[<plugin-name>]`
- the CLI parsing of …

Use `fps` configuration to store auth secrets/config

---

plugins/retrolab/fps_retrolab/routes.py

Consoles and terminals are also supported in RetroLab.

Add `consoles` and `terminals` handlers for RetroLab

---

plugins/auth/fps_auth/backends.py
plugins/auth/fps_auth/routes.py
plugins/contents/fps_contents/routes.py
plugins/jupyterlab/fps_jupyterlab/routes.py
plugins/kernels/fps_kernels/routes.py
plugins/nbconvert/fps_nbconvert/routes.py
plugins/terminals/fps_terminals/routes.py

Implement [authentication backend for no-auth](https://github.com/fastapi-users/fastapi-users/discussions/730#discussioncomment-1360817).
Not functional yet, cc @frankie567.

Rework noauth

---

.github/workflows/main.yml
plugins/auth/fps_auth/routes.py
setup.cfg

Description
---
https://github.com/jupyter-server/fps/pull/32 moved `uvicorn` and corresponding CLI to a dedicated plugin.
Use `fps_uvicorn` plugin:
- use config moved from fps to fps_uvicorn
- update dependencies
- use logger to print link in console

Use `fps_uvicorn` plugin

---

binder/postBuild
examples/jupyverse.ipynb
plugins/retrolab/fps_retrolab/routes.py

Support RetroLab in Binder

---

CHANGELOG.md

Automated Changelog Entry for 0.0.14 on main
| Version Spec | 0.0.14 |
| Since | v0.0.13 |

Automated Changelog Entry for 0.0.14 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.17 on main
| Version Spec | 0.0.17 |
| Since | v0.0.16 |

Automated Changelog Entry for 0.0.17 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.18 on main
| Version Spec | 0.0.18 |
| Since | v0.0.17 |

Automated Changelog Entry for 0.0.18 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.19 on main
| Version Spec | 0.0.19 |
| Since | v0.0.18 |

Automated Changelog Entry for 0.0.19 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.23 on main
| Version Spec | 0.0.23 |
| Since | v0.0.22 |

Automated Changelog Entry for 0.0.23 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.24 on main
| Version Spec | 0.0.24 |
| Since | v0.0.23 |

Automated Changelog Entry for 0.0.24 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.26 on main
| Version Spec | 0.0.26 |
| Since | v0.0.25 |

Automated Changelog Entry for 0.0.26 on main

---

plugins/contents/fps_contents/routes.py
plugins/contents/setup.cfg

Starlette and FastAPI require [anyio](https://anyio.readthedocs.io/en/stable/index.html), so better using it.
This PR uses the async `open_file` for better performances on file IO.

Use anyio for file IO

---

CHANGELOG.md

Automated Changelog Entry for 0.0.27 on main
| Version Spec | 0.0.27 |
| Since | v0.0.26 |

Automated Changelog Entry for 0.0.27 on main

---

binder/environment.yml

So we can test the support for translation on Binder with JupyterLab and RetroLab.

Add the french language pack on Binder

---

CHANGELOG.md

Automated Changelog Entry for 0.0.28 on main
| Version Spec | 0.0.28 |
| Since | v0.0.27 |

Automated Changelog Entry for 0.0.28 on main

---

plugins/kernels/fps_kernels/kernel_server/server.py

We can bring back "shutdown and restart" when https://github.com/jupyter/jupyter_client/issues/736 is fixed.
Fixes #156

Manually restart kernel as stop and start

---

CHANGELOG.md

Automated Changelog Entry for 0.0.29 on main
| Version Spec | 0.0.29 |
| Since | v0.0.28 |

Automated Changelog Entry for 0.0.29 on main

---

setup.cfg

Not installing the `fps-terminals` plugin on Windows at least makes it possible to run jupyverse, even though terminals won't work on this platform.
Will need to be reverted when we have a solution for #102.

Don't install fps-terminals on Windows

---

CHANGELOG.md

Automated Changelog Entry for 0.0.30 on main
| Version Spec | 0.0.30 |
| Since | v0.0.29 |

Automated Changelog Entry for 0.0.30 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.31 on main
| Version Spec | 0.0.31 |
| Since | v0.0.30 |

Automated Changelog Entry for 0.0.31 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.32 on main
| Version Spec | 0.0.32 |
| Since | v0.0.31 |

Automated Changelog Entry for 0.0.32 on main

---

plugins/kernels/fps_kernels/kernel_server/message.py
plugins/kernels/fps_kernels/kernel_server/server.py

asyncio zmq sends return awaitables, even though they _usually_ return a completed Future, due to optimizations.
Otherwise, we're creating and not awaiting Futures, which can cause ordering problems.
The layering means there are now two additional awaits for a likely already-done future. I don't know the performance cost of that. But if you care to optimize the awaits, you can do:
```python
def send_message(sock) -> Awaitable[Any]:
return sock.send(...)
...
awaitable = send_message(sock)
f = asyncio.ensure_future(awaitable) # no-op because it's already a Future, but could be a coroutine in the future
if not f.done():
await f
```
An extra await _can_ be avoided by changing the type to `->Awaitable[Any]` and `return sock.send...`, if that's preferable.
Found while looking at #183

Await zmq sends

---

CHANGELOG.md

Automated Changelog Entry for 0.0.34 on main
| Version Spec | next |
| Since | v0.0.33 |

Automated Changelog Entry for 0.0.34 on main

---

.github/workflows/main.yml
plugins/kernels/fps_kernels/kernel_driver/connect.py
plugins/kernels/fps_kernels/kernel_driver/driver.py
plugins/kernels/fps_kernels/kernel_driver/kernelspec.py
plugins/kernels/fps_kernels/kernel_driver/message.py
plugins/kernels/fps_kernels/kernel_driver/paths.py
plugins/kernels/fps_kernels/models.py
plugins/kernels/fps_kernels/routes.py
plugins/kernels/setup.cfg
setup.cfg
tests/conftest.py
tests/data/notebook0.ipynb
tests/test_contents.py
tests/test_server.py

See https://github.com/jupyter-server/jupyter_server/issues/900.

Add POST execute cell

---

tests/test_server.py

There seems to be an issue with the POST `/api/sessions` request.

Disable Windows for test_rest_api

---

plugins/jupyterlab/setup.cfg
plugins/yjs/fps_yjs/routes.py
plugins/yjs/setup.cfg

The equivalent of https://github.com/jupyter-server/jupyter_server_ydoc/pull/22.

Support global awareness

---

CHANGELOG.md

Automated Changelog Entry for 0.0.35 on main
| Version Spec | next |
| Since | v0.0.34 |

Automated Changelog Entry for 0.0.35 on main

---

.devcontainer/devcontainer.json
.devcontainer/requirements.txt

PR adds configuration to enable using [devcontainers](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers) with this repository.
They're still relatively new so a brief explanation if you haven't heard of them is that devcontainers define the configuration of a development environment which can run inside Docker (or drop-in replacements like Podman), along with information on interactions with the environment (like automatic port-forwarding of services). They make it easier for developers to get started working on a project, and help get rid of some of the issues/hard to solve bugs that come from people setting up their environments in different ways.
GitHub supports them natively via Codespaces, VSCode does as well (when opening the …

Add devcontainer configuration

---

.devcontainer/devcontainer.json

After #207 was merged I went to check if codespaces were working and there was an error as I left a podman-only command run argument in the configuration.
In the docs it's [recommended to use this configuration](https://code.visualstudio.com/remote/advancedcontainers/docker-options#_podman) when running with rootless podman, but it isn't compatible with docker, which most people (and the online based codespaces) use, so this patch comments it out and adds an explanation.

Remove Podman specific `runArgs`

---

CHANGELOG.md

Automated Changelog Entry for 0.0.36 on main
| Version Spec | next |
| Since | v0.0.35 |

Automated Changelog Entry for 0.0.36 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.38 on main
| Version Spec | next |
| Since | v0.0.37 |

Automated Changelog Entry for 0.0.38 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.39 on main
| Draft Release | https://github.com/jupyter-server/jupyverse/releases/tag/untagged-3ab212a9b6e7bceff24f  |
| Since | v0.0.38 |

Automated Changelog Entry for 0.0.39 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.40 on main
| Draft Release | https://github.com/jupyter-server/jupyverse/releases/tag/untagged-f5a9e7b92032550fbb53  |
| Since | v0.0.38 |

Automated Changelog Entry for 0.0.40 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.41 on main
| Draft Release | https://github.com/jupyter-server/jupyverse/releases/tag/untagged-ec2b55468d71d62be483  |
| Since | v0.0.40 |

Automated Changelog Entry for 0.0.41 on main

---

.github/workflows/check-release.yml
.github/workflows/main.yml
.gitignore
docs/install.md
docs/plugins/auth_base.md
fps_cli_args.toml
jupyverse/__init__.py
mkdocs.yml
plugins/auth_base/COPYING.md
plugins/auth_base/MANIFEST.in
plugins/auth_base/README.md
plugins/auth_base/fps_auth_base/__init__.py
plugins/auth_base/pyproject.toml
plugins/contents/fps_contents/routes.py
plugins/jupyterlab/fps_jupyterlab/routes.py
plugins/jupyterlab/pyproject.toml
plugins/kernels/fps_kernels/routes.py
plugins/kernels/pyproject.toml
plugins/lab/fps_lab/routes.py
plugins/lab/pyproject.toml
plugins/nbconvert/fps_nbconvert/routes.py
plugins/nbconvert/pyproject.toml
plugins/retrolab/fps_retrolab/routes.py
plugins/retrolab/pyproject.toml
plugins/terminals/fps_terminals/routes.py
plugins/terminals/pyproject.toml
plugins/yjs/fps_yjs/routes.py
plugins/yjs/pyproject.toml
pyproject.toml

Create a base auth plugin to depend on instead of jupyverse

---

CHANGELOG.md

Automated Changelog Entry for 0.0.42 on main
| Draft Release | https://github.com/jupyter-server/jupyverse/releases/tag/untagged-a907b3c75eb67e529caa  |
| Since | v0.0.41 |

Automated Changelog Entry for 0.0.42 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.0.44 on main
| Draft Release | https://github.com/jupyter-server/jupyverse/releases/tag/untagged-18a67018c66506c071c9  |
| Since | v0.0.43 |

Automated Changelog Entry for 0.0.44 on main

---

.github/workflows/main.yml
dev-environment.yml
tests/test_kernels.py

One of the tests assumes that conda was used to create the environment jupyverse is running in as it the path to the kernel is set to `os.environ["CONDA_PREFIX"] / "share/.../kernel.json"`, which will error out if `CONDA_PREFIX` is not set.
PR changes the kernelspec path to use `sys.prefix` instead of the `CONDA_PREFIX` env var. When running out of a virtual environment (be it native python venv or a conda environment) `sys.prefix` will point to the prefix for that virtual environment, not the actual system prefix.
Since `CONDA_PREFIX` is equivalent to `sys.prefix`, this doesn't change anything for that case, but lets the tests pass when running in a native python venv.
This is related to https://github.com/jupyter-server/jupyverse/pull/239 as running tests locally with hatch environments …

Use system prefix instead of conda prefix for kernel test

---

.github/workflows/main.yml
plugins/contents/fps_contents/__init__.py
plugins/contents/fps_contents/fileid.py
plugins/contents/fps_contents/watchfiles.py
plugins/contents/pyproject.toml
plugins/lab/pyproject.toml
plugins/yjs/fps_yjs/models.py
plugins/yjs/fps_yjs/routes.py
pyproject.toml
tests/test_server.py

This is the counterpart of [jupyter-server-fileid](https://github.com/jupyter-server/jupyter_server_fileid).

Implement file ID service

---

plugins/yjs/fps_yjs/routes.py

The `client` is removed here, and the `websocket` should no longer be judged to exist in the `clients`
https://github.com/y-crdt/ypy-websocket/blob/main/ypy_websocket/websocket_server.py#L147

Fix clean room never triggered

---

plugins/kernels/fps_kernels/config.py
plugins/kernels/fps_kernels/kernel_server/server.py
plugins/kernels/fps_kernels/models.py
plugins/kernels/fps_kernels/routes.py
plugins/kernels/pyproject.toml
tests/test_server.py

The path to the connection file directory must be set like this:
```bash
jupyverse --kernels.connection_path=/home/david/.local/share/jupyter/runtime
```

Add support for external kernels

---

docs/usage/multi_user.md
jupyverse_api/jupyverse_api/lab/__init__.py
plugins/auth/fps_auth/routes.py
plugins/contents/fps_contents/fileid.py
plugins/jupyterlab/pyproject.toml
plugins/lab/fps_lab/routes.py

Fix labextensions, move fileid.db to .fileid.db, update to jupyterlab v4

---

jupyverse_api/jupyverse_api/contents/models.py

Without this fix, one cannot enter an empty directory because the returned `content` is `{}` instead of `[]`.
Pydantic uses the first type in a `Union` that matches (see [documentation](https://docs.pydantic.dev/latest/usage/types/#unions)).
It seems that [smart_union](https://docs.pydantic.dev/latest/usage/model_config/#smart-union) works with Pydantic but not with FastAPI, so I just moved the `List` to the first type.

Fix contents for empty directory

---

docs/tutorials/jupyterhub_jupyverse_deployment.md
docs/tutorials/standalone_jupyverse_deployment.md
mkdocs.yml
plugins/auth_jupyterhub/COPYING.md
plugins/auth_jupyterhub/README.md
plugins/auth_jupyterhub/fps_auth_jupyterhub/__init__.py
plugins/auth_jupyterhub/fps_auth_jupyterhub/config.py
plugins/auth_jupyterhub/fps_auth_jupyterhub/db.py
plugins/auth_jupyterhub/fps_auth_jupyterhub/launch.py
plugins/auth_jupyterhub/fps_auth_jupyterhub/main.py
plugins/auth_jupyterhub/fps_auth_jupyterhub/models.py
plugins/auth_jupyterhub/fps_auth_jupyterhub/routes.py
plugins/auth_jupyterhub/pyproject.toml
pyproject.toml

Needs https://github.com/jupyterhub/jupyterhub/pull/4520.

Add fps_auth_jupyterhub plugin

---

plugins/kernels/fps_kernels/kernel_driver/driver.py
plugins/yjs/fps_yjs/ywidgets/widgets.py
pyproject.toml
tests/test_server.py

Fixes https://github.com/jupyterlab/jupyter-collaboration/issues/351.

Bump ypywidgets, fix display_output handling

---

jupyverse_api/jupyverse_api/yjs/__init__.py
plugins/yjs/fps_yjs/main.py
plugins/yjs/fps_yjs/routes.py

Closes https://github.com/jupyterlab/jupyter-collaboration/issues/366.

Add Yjs plugin configuration

---

mkdocs.yml

I noticed a small typo in the documentation.

Fixing typo in the documentation

---

plugins/yjs/fps_yjs/routes.py
plugins/yjs/fps_yjs/ywebsocket/yroom.py

Fixes the issue described in https://github.com/jupyter-server/jupyverse/issues/505.
I modified no-auth locally to remove the yjs write permission, unless if the request had a `yjs-write` header. Then, I opened two browsers, one on `localhost:8000`, connecting directly to the web server (read-only), and another on `localhost:8001`, connecting to a proxy that attached the `yjs-write` header. (read-write).
https://github.com/user-attachments/assets/d74ad39f-7f2e-4fea-8578-45bd309f6c01

Fix read/write permission issue with collaboration rooms

---

jupyverse_api/jupyverse_api/kernels/__init__.py
plugins/kernel_subprocess/fps_kernel_subprocess/kernel_subprocess.py
plugins/kernel_subprocess/fps_kernel_subprocess/main.py
plugins/kernels/fps_kernels/kernel_server/server.py
plugins/kernels/fps_kernels/routes.py
pyproject.toml

This allows to run kernels in an environment that is separate from the environment the server is running in.
Currently, only conda environments are supported, and the only supported package manager is [micromamba](https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html). Also, the only supported shell is bash. Note that [pyyaml](https://pyyaml.org) must be installed in the server environment.
A path to a environment must be passed like so:
```bash
jupyverse --set kernels.kernelenv_path=environment.yml
```

Support separate kernel environment

---

.github/workflows/test.yml
plugins/yjs/fps_yjs/routes.py
pyproject.toml

It's possible for a read-only client to make changes to a collaborative document through `SYNC_STEP2` messages, since the server only filters out `SYNC_UPDATE` types.
Minimal repro:
- Connect to room as read-only
- Make changes to local document (updates get filtered out)
- Disconnect and re-connect to the room, changes are now accepted by the server
https://github.com/user-attachments/assets/d8001a43-e174-420a-b464-6a1966ad1dae
This PR fixes that issue and makes the server also filter `SYNC_STEP2` messages from read-only clients.

Filter SYNC_STEP2 messages from read-only clients
