jupyter-server/jupyverse

- jupyverse/app.py
- jupyverse/jupyverse.py
I think in the long run we need to open a file as it's done in Jupyter Server.
> Add --open-browser option

- jupyverse/app.py
- jupyverse/jupyverse.py
- jupyverse/router.py
- jupyverse/routers/contents/routes.py
- jupyverse/routers/nbconvert/__init__.py
- jupyverse/routers/nbconvert/routes.py
- jupyverse/routers/retro_lab/routes.py
> Add nbconvert endpoints

- jupyverse/app.py
- jupyverse/jupyverse.py
- jupyverse/routers/jupyter_lab/__init__.py
- jupyverse/routers/jupyter_lab/routes.py
- jupyverse/routers/kernels/routes.py
- jupyverse/tests/conftest.py
> Support JupyterLab

- jupyverse/app.py
- jupyverse/jupyverse.py
- jupyverse/routers/jupyter_lab/routes.py
- jupyverse/routers/yjs/__init__.py
- jupyverse/routers/yjs/routes.py
> Support collaborative editing

- plugins/yjs/fps_yjs/routes.py
> Allow Yjs for documents other than notebooks

- README.md
- plugins/auth/fps_auth/models.py
- plugins/auth/fps_auth/routes.py
- plugins/jupyterlab/fps_jupyterlab/routes.py
- plugins/kernels/setup.py
- plugins/retrolab/fps_retrolab/routes.py
- plugins/terminals/fps_terminals/models.py
- plugins/terminals/fps_terminals/routes.py
- plugins/terminals/fps_terminals/server.py
- plugins/terminals/setup.py
> Implement terminals

- plugins/contents/fps_contents/routes.py
See https://github.com/jupyterlab/jupyterlab/issues/11005
> Don't save orig_nbformat in notebook metadata

- plugins/auth/fps_auth/models.py
- plugins/auth/setup.py
- plugins/contents/fps_contents/routes.py
- plugins/jupyterlab/fps_jupyterlab/routes.py
- plugins/yjs/fps_yjs/routes.py
https://github.com/tiangolo/fastapi/pull/3879 needs to be merged first.
> Fix content API with sub-directories

- .github/workflows/main.yml
- README.md
- binder/environment.yml
- binder/postBuild
- examples/jupyverse.ipynb
- plugins/jupyterlab/fps_jupyterlab/config.py
- plugins/jupyterlab/fps_jupyterlab/routes.py
Not fully functional, but it's a start. Jupyverse runs in a notebook.
It seems the JupyterLab `jupyverse-auth` extension is not installed.
There are also issues with workspaces, as there is already a default workspace for the window where jupyverse is running.
> Add Binder

- .github/workflows/main.yml
- README.md
- binder/postBuild
- plugins/auth/fps_auth/routes.py
- plugins/jupyterlab/fps_jupyterlab/routes.py
The request asking for the JLab page should allow for an unauthenticated user, at least until we have a proper login page.
> Allow None user to load JLab page

- plugins/jupyterlab/fps_jupyterlab/routes.py
- plugins/jupyterlab/setup.py
> Implement jlab translations API

- plugins/auth/fps_auth/backends.py
> Fix OpenAPI generation for NoAuthAuthentication

- README.md
- plugins/retrolab/fps_retrolab/config.py
- plugins/retrolab/fps_retrolab/routes.py
- plugins/retrolab/setup.py
> Improve retrolab

- .github/workflows/main.yml
- plugins/kernels/fps_kernels/kernel_server/server.py
- setup.cfg
- tests/conftest.py
- tests/test_auth.py
- tests/test_kernels.py
We should add tests, since it is critical for security reasons.
> Filter out messages

- plugins/retrolab/fps_retrolab/routes.py
> Support editing file

- CHANGELOG.md
Automated Changelog Entry for 0.0.20 on main
| Version Spec | 0.0.20 |
| Since | v0.0.19 |
> Automated Changelog Entry for 0.0.20 on main

- CHANGELOG.md
Automated Changelog Entry for 0.0.21 on main
| Version Spec | 0.0.21 |
| Since | v0.0.20 |
> Automated Changelog Entry for 0.0.21 on main

- CHANGELOG.md
Automated Changelog Entry for 0.0.22 on main
| Version Spec | 0.0.22 |
| Since | v0.0.21 |
> Automated Changelog Entry for 0.0.22 on main

- CHANGELOG.md
Automated Changelog Entry for 0.0.25 on main
| Version Spec | 0.0.25 |
| Since | v0.0.24 |
> Automated Changelog Entry for 0.0.25 on main

- plugins/auth/fps_auth/backends.py
> Fix create_guest

- plugins/jupyterlab/fps_jupyterlab/config.py
- plugins/jupyterlab/fps_jupyterlab/routes.py
- plugins/lab/fps_lab/routes.py
- plugins/lab/fps_lab/utils.py
- plugins/retrolab/fps_retrolab/routes.py
Co-authored-by: Carlos Herrero <carlosherrerocontact@gmail.com>
> Support JupyterLab's dev mode, improve extension system

- plugins/auth/setup.cfg
> Pin fastapi-users < 9

- tests/test_server.py
- tests/test_settings.py
> Fix settings test

- plugins/lab/fps_lab/routes.py
- plugins/lab/setup.cfg
> Fix language setting

- plugins/kernels/fps_kernels/kernel_server/connect.py
- plugins/kernels/fps_kernels/kernel_server/message.py
- plugins/kernels/fps_kernels/kernel_server/server.py
- plugins/kernels/fps_kernels/routes.py
See https://github.com/jupyter-server/jupyter_server/pull/657
> Protocol alignment

- plugins/kernels/fps_kernels/kernel_server/connect.py
- plugins/kernels/fps_kernels/kernel_server/server.py
> Support stdin channel

- .github/workflows/main.yml
- plugins/auth/README.md
- plugins/auth/fps_auth/config.py
- plugins/auth/setup.cfg
- plugins/contents/README.md
- plugins/contents/setup.cfg
- plugins/jupyterlab/README.md
- plugins/jupyterlab/setup.cfg
- plugins/kernels/README.md
- plugins/kernels/setup.cfg
- plugins/lab/README.md
- plugins/lab/setup.cfg
- plugins/login/README.md
- plugins/login/setup.cfg
- plugins/nbconvert/README.md
- plugins/nbconvert/setup.cfg
- plugins/retrolab/README.md
- plugins/retrolab/setup.cfg
- plugins/terminals/README.md
- plugins/terminals/setup.cfg
- plugins/yjs/README.md
- plugins/yjs/setup.cfg
- setup.cfg
- tests/test_kernels.py
- tests/test_settings.py
> Support python 3.7

- plugins/contents/fps_contents/routes.py
> Handle symlinks

- plugins/login/MANIFEST.in
- plugins/login/setup.cfg
- setup.cfg
Workaround for https://github.com/pypa/setuptools/issues/3200.
> Include explicit package data

- plugins/contents/fps_contents/models.py
- plugins/contents/fps_contents/routes.py
- plugins/jupyterlab/setup.cfg
- plugins/yjs/fps_yjs/routes.py
- plugins/yjs/setup.cfg
This PR updates jupyverse with the following PRs in JupyterLab:
- https://github.com/jupyterlab/jupyterlab/pull/11599
- https://github.com/jupyterlab/jupyterlab/pull/12360
> Load/auto-save document from the back-end using y-py

- plugins/yjs/fps_yjs/routes.py
Similar to https://github.com/jupyterlab/jupyterlab/pull/12600.
> Store Y updates

- plugins/auth/setup.cfg
- plugins/lab/fps_lab/routes.py
See https://github.com/fastapi-users/fastapi-users/issues/1048.
> Pin fastapi-users >=10.1.4

- plugins/auth/fps_auth/fixtures.py
- plugins/auth/fps_auth/routes.py
- plugins/auth_fief/fps_auth_fief/routes.py
Parameters are query parameters, not body parameters.
> Fix /api/me permissions parameters

- plugins/auth/fps_auth/backends.py
- pyproject.toml
> Update to FastAPI 0.95

- plugins/yjs/fps_yjs/routes.py
- plugins/yjs/pyproject.toml
- tests/test_server.py
See https://github.com/y-crdt/ypy-websocket/pull/77.
> Support ypy-websocket v0.12

- plugins/contents/pyproject.toml
- plugins/resource_usage/pyproject.toml
AnyIO [v4.0.0](https://pypi.org/project/anyio/4.0.0/) is out.
> Pin anyio<5

- plugins/kernels/fps_kernels/kernel_driver/driver.py
- plugins/yjs/fps_yjs/routes.py
- plugins/yjs/fps_yjs/ywidgets/widgets.py
> Make ypywidgets optional

- README.md
- pyproject.toml
> Update documentation URL

- plugins/auth_jupyterhub/pyproject.toml
Fixes https://github.com/jupyterhub/jupyterhub/issues/5008.
> Fix fps-auth-jupyterhub dependency

- plugins/yjs/fps_yjs/routes.py
> Fix document duplication with out-of-band changes
